<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Test</RootNamespace>
        <LangVersion>default</LangVersion>
        <Authors>Traxx186</Authors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\AdventOfCode.AoC2023\AdventOfCode.AoC2023.csproj" PrivateAssets="All" />
        <ProjectReference Include="..\src\AdventOfCode.AoC2024\AdventOfCode.AoC2024.csproj" PrivateAssets="All" />
        <ProjectReference Include="..\src\AdventOfCode.AoC2025\AdventOfCode.AoC2025.csproj" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Include="*\**\Data\*.txt" CopyToOutputDirectory="PreserveNewest" />
        <None Update="AoC2025\Data\day_03.txt">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
