<Project>

    <PropertyGroup>
        <RootNamespace>$(MSBuildProjectName)</RootNamespace>
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <RepositoryUrl>https://github.com/Traxx186/advent-of-code</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>Traxx186</Authors>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Data\*.txt" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
